# Generated by Django 6.0.3 on 2026-04-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writesphere", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
